version: '3.8'
services:
  stat-service:
    build: ./service-stat/http-service
    image: stat-service
    container_name: stat-service
    ports:
      - "9090:9090"
    depends_on:
      - db-stat

  service-main:
    build: ./service-main
    image: service-main
    container_name: service-main
    ports:
      - "8080:8080"
    depends_on:
      - db-main

  db-stat:
    image: postgres
    container_name: db-stat
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stat
      - POSTGRES_USER=stat
      - POSTGRES_PASSWORD=stat

  db-main:
    image: postgres
    container_name: db-main
    ports:
      - "6542:5433"
    environment:
      - POSTGRES_DB=main
      - POSTGRES_USER=main
      - POSTGRES_PASSWORD=main