DROP TABLE IF EXISTS requests CASCADE;

CREATE TABLE IF NOT EXISTS requests
(
    id        BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    app       VARCHAR(255) NOT NULL,
    uri       VARCHAR(255) NOT NULL,
    ip        VARCHAR(255) NOT NULL,
    timestamp TIMESTAMP WITHOUT TIME ZONE
);